# spring.application.name=hexagonal-architecture

spring:
    application:
        name: hexagonal-architecture

    data:
        mongodb:
            database: admin
            uri: ${MONGO_DB_URI:mongodb://admin:root@localhost:27017}

jwt:
    private:
        key: ${JWT_PRIVATE_KEY_PATH:classpath:app.key}
    public:
        key: ${JWT_PUBLIC_KEY_PATH:classpath:app.pub}     
